version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/bigmelo-api
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop-queue.sh
    - timeout: 300
  AfterInstall:
    - location: scripts/start-queue.sh
    - timeout: 300